### ISSUE TITLE
Remove Choose-response-results section

### ISSUE THREAD

**Issue by el-sonny** [spaceship-labs/salama#4]
Go straight to the "get involved" section. Comment or factor that section into template for now.

**Comment by tugorez** [comment]
Sorry i don't get it . Could you be more specific?

**Comment by el-sonny** [comment]
In this view:

http://spaceship-labs.github.io/salama/#/evaluation

Just comment out/remove the blue section that says "choose response, results" so that it goes straight from the menu to the survey.
